version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - mongo-store:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
volumes:
  mongo-store: